<?php

declare(strict_types=1);

/**
 * @file
 * Provides a json data entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function json_data_theme(): array {
  return [
    'json_data' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for json data templates.
 *
 * Default template: json-data.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the json data information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_json_data(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function json_data_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish json datas.
      $storage = \Drupal::entityTypeManager()->getStorage('json_data');
      $json_data_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($json_data_ids) as $json_data) {
        $json_data->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize json datas.
      $storage = \Drupal::entityTypeManager()->getStorage('json_data');
      $json_data_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($json_data_ids) as $json_data) {
        $json_data->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function json_data_user_predelete(UserInterface $account): void {
  // Delete json datas that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('json_data');
  $json_data_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($json_data_ids)
  );
  // Delete old revisions.
  $json_data_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  foreach (array_keys($json_data_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}
